-- MySQL Script generated by MySQL Workbench
-- Fri 23 Sep 2022 03:57:49 PM -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema e-commerce
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema e-commerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `e-commerce` ;
USE `e-commerce` ;

-- -----------------------------------------------------
-- Table `e-commerce`.`Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e-commerce`.`Category` ;

CREATE TABLE IF NOT EXISTS `e-commerce`.`Category` (
  `name` VARCHAR(32) NOT NULL,
  `sizes` VARCHAR(128) NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e-commerce`.`Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e-commerce`.`Product` ;

CREATE TABLE IF NOT EXISTS `e-commerce`.`Product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `description` TEXT NULL,
  `price` FLOAT NOT NULL,
  `images` TEXT NULL,
  `brand` VARCHAR(64) NULL,
  `category` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Product_Category1_idx` (`category` ASC) VISIBLE,
  CONSTRAINT `fk_Product_Category1`
    FOREIGN KEY (`category`)
    REFERENCES `e-commerce`.`Category` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e-commerce`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e-commerce`.`User` ;

CREATE TABLE IF NOT EXISTS `e-commerce`.`User` (
  `mail` VARCHAR(64) NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `surname` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`mail`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e-commerce`.`Purchase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e-commerce`.`Purchase` ;

CREATE TABLE IF NOT EXISTS `e-commerce`.`Purchase` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_mail` VARCHAR(64) NOT NULL,
  `product_id` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `amount` SMALLINT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_User_has_Product_Product1_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_User_has_Product_User1_idx` (`user_mail` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_Product_User1`
    FOREIGN KEY (`user_mail`)
    REFERENCES `e-commerce`.`User` (`mail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Product_Product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `e-commerce`.`Product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
